name: Docker Build and Upload

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t japaschool/sadhana:latest .

      - name: Push Docker image
        run: docker push japaschool/sadhana:latest

      - name: Configure SSH
        run: |
              mkdir -p ~/.ssh/
              echo "$SSH_KEY" > ~/.ssh/sadhana.key
              chmod 600 ~/.ssh/sadhana.key
              cat >>~/.ssh/config <<END
              Host sadhana
                HostName $SSH_HOST
                User $SSH_USER
                IdentityFile ~/.ssh/sadhana.key
                StrictHostKeyChecking no
              END
        env:
              SSH_USER: ${{ secrets.SSH_USERNAME }}
              SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              SSH_HOST: ${{ secrets.SSH_HOST }}
              
      - name: Executing update script
        run: ssh sadhana 'bash -s < cd /home/sadhana/docker ; docker-compose up -d'
