name: Test it

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
              mkdir -p ~/.ssh/
              echo "$SSH_KEY" > ~/.ssh/sadhana.key
              chmod 600 ~/.ssh/sadhana.key
              cat >>~/.ssh/config <<END
              Host sadhana
                HostName $SSH_HOST
                User $SSH_USER
                IdentityFile ~/.ssh/sadhana.key
                StrictHostKeyChecking no
              END
        env:
              SSH_USER: ${{ secrets.SSH_USERNAME }}
              SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              SSH_HOST: ${{ secrets.SSH_HOST }}
              
      - name: Executing update script
        run: ssh sadhana -c 'DOCKER_HOST=unix:///run/user/1108/docker.sock /usr/bin/docker-compose -f /home/sadhana/docker/docker-compose.yml up -d'
